package lk.ijse.Fusion.lk.ijse.Fusion.Util;

public enum Routes {
    MAINPAGE,SIGNUPPAGE,DASHBOARD,PLACEORDER,STOCKDASH,IT_MANAGERDASH,ITEM,ORDERS,EMPLOYEE,SALARY,CUSTOMER,PAYMENT,SUPPLIER,ATTENDS,STOCK,DELIVERY,RETURN
}
